version: "3"

networks:
  localNetwork:
    name: localNetwork    

services:
  localstack:
    #container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      #- "127.0.0.1:53:53"                # only required for Pro (DNS)
      #- "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      #- "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      #- "127.0.0.1:4510-4559:4510-4559"  # external service port range
      #- "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
      - "4566-4597:4566-4597"
    environment:
      DEBUG: 1 #${DEBUG-1}
      SERVICES: 'sns,sqs'
      DEFAULT_REGION: us-east-1
      DOCKER_HOST: unix:///var/run/docker.sock
      EXTRA_CORS_ALLOWED_ORIGINS: '*'
      #EXTRA_CORS_ALLOWED_HEADERS: ''
      #DATA_DIR: ${LOCALSTACK_DATA-}
    volumes:
      - "/tmp:/tmp/localstack"
      #- "/var/run/docker.sock:/var/run/docker.sock"
    entrypoint: 
     - awslocal sqs create-queue --queue-name sample-queue && awslocal sqs create-queue --queue-name sample-queue-fifo